version: "3.8"
services:
  es001:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es001
    environment:
      discovery.type: single-node
      # TODO: try this in the future
      # node.name: es001
      # cluster.name: es-docker-cluster
      # cluster.initial_master_nodes: es001
      # bootstrap.memory_lock: "true"
      # ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data001:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib001:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kib001
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es001:9200
      ELASTICSEARCH_HOSTS: http://es001:9200
    networks:
      - elastic

volumes:
  data001:
    driver: local

networks:
  elastic:
    driver: bridge